#!/usr/bin/env bash
# Fetch the whitepaper from the repository that owns it, for MkDocs to render.
#
# The wiki renders it in its own theme; it does not keep a copy. `docs/whitepaper.md` is
# generated and git-ignored on purpose -- a committed copy is a second source, and a second
# source is how the published document ended up a full version behind the one under review.
set -euo pipefail
SRC="https://raw.githubusercontent.com/pezkuwichain/pezkuwi-DKS/main/docs/whitepaper/whitepaper.md"
OUT="docs/whitepaper.md"

tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
curl -fsS --max-time 90 "$SRC" -o "$tmp"

# A GitHub error page and a truncated download both arrive with exit code zero.
grep -q '^# PezkuwiChain' "$tmp" || { echo "fetch-whitepaper: not the whitepaper" >&2; exit 1; }
[ "$(wc -c < "$tmp")" -gt 20000 ] || { echo "fetch-whitepaper: too small" >&2; exit 1; }

{
	echo "<!-- Generated by scripts/fetch-whitepaper.sh. Do not edit: edit the source. -->"
	echo "<!-- Source: $SRC -->"
	echo
	cat "$tmp"
} > "$OUT"
echo "fetch-whitepaper: $(wc -c < "$OUT") bytes"
